apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
    type: backend
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: employee-service
      type: backend
  template:
    metadata:
      labels:
        app: employee-service
        type: backend
    spec:
      containers:
        - image: prateek91sharma/kubernetes_advanced_2025:latest
          imagePullPolicy: Always
          name: employee-service
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
              name: app-port
          envFrom:
            - secretRef:
                name: employee-service-secrets
            - configMapRef:
                name: employee-service-config
