apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee-service
    type: backend
spec:
  type: NodePort
  selector:
    app: employee-service
    type: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
